spring:
  datasource:
    druid:
      url: jdbc:mysql://8.131.76.86:3306/db_shrio2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: xyq
      password: 2550315206
      initial-size: 1
      min-idle: 1
      max-active: 20
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.xyq.shiro3.beans
